### ISSUE TITLE
"libOpenCL-pixel.so" not found

### ISSUE THREAD

**Issue by GrishTad** [bkunters/TFLite4Unity#2]
Thank you for doing this job.
I have a problem with the running of the project on Google pixel 2 Android 10, with Unity 2019.2.5 . I have used the development branch. Here is the error that I am getting from logcat.

`AndroidJavaException: java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: OpenCL library not loaded - dlopen failed: library "libOpenCL-pixel.so" not found
Falling back to OpenGL
TfLiteGpuDelegate Invoke: Write to buffer failed. Source data is larger than buffer.`

Project is working properly on Google pixel 3 android 10 without changes.

Thanks in advance

**Comment by bkunters** [comment]
Hi,

There is an app called OpenCL-Z on the play store. I have already seen in the web that this might be an issue for pixel2 phones as they are using renderscript instead of using opencl.
Just check through the app if it has libOpenCL.so or sth. similar

These might be already fixed in the later versions of tf lite. Currently we are using the alpha version. I will try to integrate the later versions.

**Comment by bkunters** [comment]
Hi @GrishTad ,

I have updated the plugin to tflite 2.0.0. Could you try again with your device to check if it is working now ? Just pull the develop branch.
